Repository js-sdsl/js-sdsl, pull requests merged in 2022-09, with the labels that each got.

#15 build: version 4.1.4
  CHANGELOG.md
  package.json
  src/container/ContainerBase/index.ts
  src/container/HashContainer/Base/index.ts
  src/container/HashContainer/HashMap.ts
  src/container/HashContainer/HashSet.ts
  src/container/OtherContainer/Queue.ts
  src/container/SequentialContainer/Base/RandomIterator.ts
  src/container/SequentialContainer/Deque.ts
  src/container/SequentialContainer/LinkList.ts
  src/container/SequentialContainer/Vector.ts
  src/container/TreeContainer/Base/TreeIterator.ts
  src/container/TreeContainer/Base/index.ts
  src/container/TreeContainer/OrderedMap.ts
  src/container/TreeContainer/OrderedSet.ts
  src/index.ts
  test/HashContainerTest/HashMap.test.ts
  test/HashContainerTest/HashSet.test.ts
  test/OtherContainerTest/Queue.test.ts
  test/OtherContainerTest/Stack.test.ts
  test/OtherTest/iterator.test.ts
  test/SequentialContainerTest/Deque.test.ts
  test/SequentialContainerTest/LinkList.test.ts
  test/SequentialContainerTest/SequentialContainer.test.ts
  test/TreeContainerTest/OrderedMap.test.ts
Labels: bug, enhancement

#25 test: make hashcontainer tests stronger
  src/container/HashContainer/HashMap.ts
  src/container/HashContainer/HashSet.ts
  test/HashContainerTest/HashMap.test.ts
  test/HashContainerTest/HashSet.test.ts
Labels: coverage, refactor

#24 perf: apply transformer and const enum optimize
  .eslintrc.json
  gulpfile.ts
  package.json
  rollup.config.ts
  src/container/ContainerBase/index.ts
  src/container/HashContainer/Base/index.ts
  src/container/HashContainer/HashMap.ts
  src/container/HashContainer/HashSet.ts
  src/container/SequentialContainer/Base/RandomIterator.ts
  src/container/SequentialContainer/Deque.ts
  src/container/SequentialContainer/LinkList.ts
  src/container/SequentialContainer/Vector.ts
  src/container/TreeContainer/Base/TreeIterator.ts
  src/container/TreeContainer/Base/TreeNode.ts
  src/container/TreeContainer/Base/index.ts
  src/container/TreeContainer/OrderedMap.ts
  src/container/TreeContainer/OrderedSet.ts
  src/index.ts
  src/utils/checkParams.macro.ts
  test/HashContainerTest/HashMap.test.ts
  test/HashContainerTest/HashSet.test.ts
  test/TreeContainerTest/OrderedMap.test.ts
  tsconfig.cjs.json
  tsconfig.dev.json
  tsconfig.esm.json
  tsconfig.json
  tsconfig.performance.json
  yarn.lock
Labels: enhancement, coverage, performance, refactor

#37 docs: update changelog for #24
  CHANGELOG.md
Labels: documentation

#39 perf: remove some useless export
  src/index.ts
  test/OtherTest/iterator.test.ts
Labels: refactor, configure

#14 feat: add tree iterator index
  CHANGELOG.md
  src/container/HashContainer/Base/index.ts
  src/container/HashContainer/HashMap.ts
  src/container/HashContainer/HashSet.ts
  src/container/OtherContainer/PriorityQueue.ts
  src/container/OtherContainer/Queue.ts
  src/container/OtherContainer/Stack.ts
  src/container/SequentialContainer/Base/RandomIterator.ts
  src/container/SequentialContainer/Base/index.ts
  src/container/SequentialContainer/Deque.ts
  src/container/SequentialContainer/LinkList.ts
  src/container/SequentialContainer/Vector.ts
  src/container/TreeContainer/Base/TreeIterator.ts
  src/container/TreeContainer/Base/TreeNode.ts
  src/container/TreeContainer/Base/index.ts
  src/container/TreeContainer/OrderedMap.ts
  src/container/TreeContainer/OrderedSet.ts
  src/utils/checkParams.macro.ts
  test/TreeContainerTest/OrderedMap.test.ts
  test/TreeContainerTest/OrderedSet.test.ts
Labels: enhancement, refactor

#42 refactor: add _ perfix for private and protected member
  gulpfile.ts
  package.json
  src/container/ContainerBase/index.ts
  src/container/HashContainer/Base/index.ts
  src/container/HashContainer/HashMap.ts
  src/container/HashContainer/HashSet.ts
  src/container/OtherContainer/PriorityQueue.ts
  src/container/OtherContainer/Queue.ts
  src/container/OtherContainer/Stack.ts
  src/container/SequentialContainer/Base/RandomIterator.ts
  src/container/SequentialContainer/Deque.ts
  src/container/SequentialContainer/LinkList.ts
  src/container/SequentialContainer/Vector.ts
  src/container/TreeContainer/Base/TreeIterator.ts
  src/container/TreeContainer/Base/index.ts
  src/container/TreeContainer/OrderedMap.ts
  src/container/TreeContainer/OrderedSet.ts
  src/utils/checkParams.macro.ts
  test/HashContainerTest/HashMap.test.ts
  test/HashContainerTest/HashSet.test.ts
  tsconfig.json
  yarn.lock
Labels: documentation, performance, refactor, configure

#44 perf: do some perf
  src/container/ContainerBase/index.ts
  src/container/HashContainer/Base/index.ts
  src/container/OtherContainer/Queue.ts
  src/container/SequentialContainer/Base/RandomIterator.ts
  src/container/SequentialContainer/Deque.ts
  src/container/SequentialContainer/LinkList.ts
  src/container/SequentialContainer/Vector.ts
  src/container/TreeContainer/Base/TreeIterator.ts
  src/container/TreeContainer/Base/index.ts
  src/container/TreeContainer/OrderedMap.ts
  src/container/TreeContainer/OrderedSet.ts
Labels: performance, refactor

#46 build: publish@4.1.5-beta.0 [dev]
  CHANGELOG.md
  package.json
Labels: publish

#48 fix: get wrong tree index when size is 0
  CHANGELOG.md
  src/container/TreeContainer/Base/TreeIterator.ts
  test/TreeContainerTest/OrderedSet.test.ts
Labels: bug

#45 test: migrate jest to mocha
  .github/workflows/build.yml
  .github/workflows/test.yml
  .gitignore
  .nycrc.json
  jest.config.ts
  karma.conf.ts
  package.json
  performance/HashContainerTest/HashMap.performance.ts
  performance/HashContainerTest/HashSet.performance.ts
  performance/OtherContainerTest/PriorityQueue.performance.ts
  performance/OtherContainerTest/Queue.performance.ts
  performance/OtherContainerTest/Stack.performance.ts
  performance/SequentialContainerTest/SequentialContainer.performance.ts
  performance/TreeContainerTest/OrderedMap.performance.ts
  performance/TreeContainerTest/OrderedSet.performance.ts
  performance/index.ts
  src/container/SequentialContainer/LinkList.ts
  src/container/TreeContainer/Base/TreeIterator.ts
  src/container/TreeContainer/Base/TreeNode.ts
  src/container/TreeContainer/Base/index.ts
  src/container/TreeContainer/OrderedMap.ts
  src/container/TreeContainer/OrderedSet.ts
  test/HashContainerTest/HashMap.test.ts
  test/HashContainerTest/HashSet.test.ts
  test/OtherContainerTest/PriorityQueue.test.ts
  test/OtherContainerTest/Queue.test.ts
  test/OtherContainerTest/Stack.test.ts
  test/OtherTest/constructor.test.ts
  test/OtherTest/iterator.test.ts
  test/OtherTest/symbol-iterator.test.ts
  test/SequentialContainerTest/Deque.test.ts
  test/SequentialContainerTest/LinkList.test.ts
  test/SequentialContainerTest/SequentialContainer.test.ts
  test/TreeContainerTest/OrderedMap.test.ts
  test/TreeContainerTest/OrderedSet.test.ts
  yarn.lock
Labels: coverage, refactor, configure

#36 feat: module isolation
  conf/isolate.config.json
  gulpfile.ts
  package.json
  tools/buildFactory.ts
  tools/createTask.ts
  tools/publishIsolate.ts
  tools/tsTreeshaker.ts
  tsconfig.json
  yarn.lock
Labels: enhancement, refactor, configure

#53 chore: update workflow for isolate
  .github/workflows/build.yml
  gulpfile.ts
  tools/buildFactory.ts
  tools/publishIsolate.ts
  tools/tsTreeShaker.ts
Labels: configure

#52 feat: make heap stronger
  CHANGELOG.md
  src/container/OtherContainer/PriorityQueue.ts
  test/OtherContainerTest/PriorityQueue.test.ts
Labels: enhancement

#57 docs: update typo
  package.json
  src/container/ContainerBase/index.ts
  src/container/HashContainer/Base/index.ts
  src/container/OtherContainer/PriorityQueue.ts
  src/container/SequentialContainer/Base/RandomIterator.ts
  src/container/SequentialContainer/LinkList.ts
  src/container/TreeContainer/Base/TreeIterator.ts
  src/container/TreeContainer/Base/TreeNode.ts
  src/container/TreeContainer/Base/index.ts
  src/container/TreeContainer/OrderedMap.ts
  src/container/TreeContainer/OrderedSet.ts
  yarn.lock
Labels: documentation, dependencies, configure

#54 build: publish@4.1.5 beta.1 [dev]
  CHANGELOG.md
  conf/isolate.config.json
  package.json
Labels: publish
