Repository js-sdsl/js-sdsl, pull requests merged in 2022-10, with the labels that each got.

#55 build: publish@4.1.5
  .github/workflows/build.yml
  .github/workflows/test.yml
  .gitignore
  .nycrc.json
  CHANGELOG.md
  conf/isolate.config.json
  gulpfile.ts
  jest.config.ts
  karma.conf.ts
  package.json
  performance/HashContainerTest/HashMap.performance.ts
  performance/HashContainerTest/HashSet.performance.ts
  performance/OtherContainerTest/PriorityQueue.performance.ts
  performance/OtherContainerTest/Queue.performance.ts
  performance/OtherContainerTest/Stack.performance.ts
  performance/SequentialContainerTest/SequentialContainer.performance.ts
  performance/TreeContainerTest/OrderedMap.performance.ts
  performance/TreeContainerTest/OrderedSet.performance.ts
  performance/index.ts
  src/container/ContainerBase/index.ts
  src/container/HashContainer/Base/index.ts
  src/container/OtherContainer/PriorityQueue.ts
  src/container/SequentialContainer/Base/RandomIterator.ts
  src/container/SequentialContainer/LinkList.ts
  src/container/TreeContainer/Base/TreeIterator.ts
  src/container/TreeContainer/Base/TreeNode.ts
  src/container/TreeContainer/Base/index.ts
  src/container/TreeContainer/OrderedMap.ts
  src/container/TreeContainer/OrderedSet.ts
  test/HashContainerTest/HashMap.test.ts
  test/HashContainerTest/HashSet.test.ts
  test/OtherContainerTest/PriorityQueue.test.ts
  test/OtherContainerTest/Queue.test.ts
  test/OtherContainerTest/Stack.test.ts
  test/OtherTest/constructor.test.ts
  test/OtherTest/iterator.test.ts
  test/OtherTest/symbol-iterator.test.ts
  test/SequentialContainerTest/Deque.test.ts
  test/SequentialContainerTest/LinkList.test.ts
  test/SequentialContainerTest/SequentialContainer.test.ts
  test/TreeContainerTest/OrderedMap.test.ts
  test/TreeContainerTest/OrderedSet.test.ts
  tools/buildFactory.ts
  tools/createTask.ts
  tools/publishIsolate.ts
  tools/tsTreeShaker.ts
  tsconfig.json
  yarn.lock
Labels: publish

#60 build: publish isolate
  .github/workflows/build.yml
  tools/publishIsolate.ts
Labels: bug, configure, publish

#59 docs: add isolate packages info to readme
  README.md
  README.zh-CN.md
Labels: documentation

#58 chore: add sourcemap for ts
  gulpfile.ts
  tools/buildFactory.ts
Labels: configure

#63 docs: add examples for api in typedoc
  .github/workflows/deploy-preview.yml
  src/container/ContainerBase/index.ts
  src/container/HashContainer/Base/index.ts
  src/container/HashContainer/HashMap.ts
  src/container/HashContainer/HashSet.ts
  src/container/OtherContainer/PriorityQueue.ts
  src/container/SequentialContainer/Base/index.ts
  src/container/SequentialContainer/LinkList.ts
  src/container/TreeContainer/Base/TreeIterator.ts
  src/container/TreeContainer/Base/TreeNode.ts
  src/container/TreeContainer/Base/index.ts
  src/container/TreeContainer/OrderedMap.ts
  src/container/TreeContainer/OrderedSet.ts
Labels: documentation

#67 ci: add deploy preview permission
  .github/workflows/deploy-preview.yml
Labels: configure

#66 chore: upgrade browserslist
  .browserslistrc
  .github/workflows/test.yml
  README.md
  README.zh-CN.md
  karma.conf.ts
  package.json
  performance/index.ts
  test/TreeContainerTest/OrderedMap.test.ts
  test/TreeContainerTest/OrderedSet.test.ts
  yarn.lock
Labels: dependencies, configure

#71 ci: add compress size action
  .github/workflows/compressed-size.yml
  .github/workflows/deploy-preview.yml
  package.json
Labels: configure

#75 ci: optimize ci
  .github/workflows/build.yml
  .github/workflows/compressed-size.yml
  .github/workflows/deploy-preview.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: configure

#76 refactor: change iterator export to export type
  src/container/SequentialContainer/Deque.ts
  src/container/SequentialContainer/LinkList.ts
  src/container/SequentialContainer/Vector.ts
  src/container/TreeContainer/OrderedMap.ts
  src/container/TreeContainer/OrderedSet.ts
Labels: refactor

#62 feat: type level tree shaking for isolate packages
  conf/isolate.config.json
  gulpfile.ts
  package.json
  tools/buildFactory.ts
  tools/createTask.ts
  tools/exportTransformer.ts
  tools/tsTreeShaker.ts
  yarn.lock
Labels: refactor, configure

#77 test: add isolation test
  .github/workflows/build.yml
  .github/workflows/compressed-size.yml
  .github/workflows/test.yml
  karma.conf.ts
  package.json
  test/IsolationTest/index.ts
Labels: coverage, configure

#78 docs: update readme
  .gitpod.yml
  README.md
  README.zh-CN.md
Labels: documentation

#82 ci: optimize workflow
  .github/workflows/codeql-analysis.yml
  .gitpod.yml
Labels: configure

#88 feat: add `this` param for `forEach` function
  CHANGELOG.md
  karma.conf.ts
  src/container/ContainerBase/index.ts
  src/container/HashContainer/Base/index.ts
  src/container/HashContainer/HashMap.ts
  src/container/HashContainer/HashSet.ts
  src/container/SequentialContainer/Deque.ts
  src/container/SequentialContainer/LinkList.ts
  src/container/SequentialContainer/Vector.ts
  src/container/TreeContainer/OrderedMap.ts
  src/container/TreeContainer/OrderedSet.ts
  test/OtherTest/symbol-iterator.test.ts
  yarn.lock
Labels: documentation, coverage, configure

#90 ci: fix wrong config for deploy
  .github/workflows/build.yml
  .github/workflows/deploy-preview.yml
Labels: bug, configure

#91 docs: improve readme
  README.md
  README.zh-CN.md
Labels: documentation

#100 ci: fix deploy workflow
  .github/workflows/deploy-preview.yml
Labels: configure

#101 ci: fix pr preview error
  .github/workflows/deploy-preview.yml
Labels: configure

#102 ci: fix pr preview error
  .github/workflows/deploy-preview.yml
Labels: configure

#104 build: publish@4.2.0-beta.0 [dev]
  CHANGELOG.md
  conf/isolate.config.json
  package.json
Labels: publish

#99 build: publish@4.2.0-beta.0
  .browserslistrc
  .github/FUNDING.yml
  .github/workflows/build.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/compressed-size.yml
  .github/workflows/deploy-preview.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .gitpod.yml
  CHANGELOG.md
  README.md
  README.zh-CN.md
  conf/isolate.config.json
  conf/umd-banner.txt
  gulpfile.ts
  karma.conf.ts
  package.json
  performance/index.ts
  src/container/ContainerBase/index.ts
  src/container/HashContainer/Base/index.ts
  src/container/HashContainer/HashMap.ts
  src/container/HashContainer/HashSet.ts
  src/container/OtherContainer/PriorityQueue.ts
  src/container/SequentialContainer/Base/index.ts
  src/container/SequentialContainer/Deque.ts
  src/container/SequentialContainer/LinkList.ts
  src/container/SequentialContainer/Vector.ts
  src/container/TreeContainer/Base/TreeIterator.ts
  src/container/TreeContainer/Base/TreeNode.ts
  src/container/TreeContainer/Base/index.ts
  src/container/TreeContainer/OrderedMap.ts
  src/container/TreeContainer/OrderedSet.ts
  test/IsolationTest/index.ts
  test/OtherTest/symbol-iterator.test.ts
  test/TreeContainerTest/OrderedMap.test.ts
  test/TreeContainerTest/OrderedSet.test.ts
  tools/buildFactory.ts
  tools/createTask.ts
  tools/exportTransformer.ts
  tools/publishIsolate.ts
  tools/tsTreeShaker.ts
  tsconfig.json
  yarn.lock
Labels: publish

#109 refactor: change hash container implement method
  karma.conf.ts
  performance/HashContainerTest/HashMap.performance.ts
  performance/HashContainerTest/HashSet.performance.ts
  performance/index.ts
  src/container/HashContainer/Base/index.ts
  src/container/HashContainer/HashMap.ts
  src/container/HashContainer/HashSet.ts
  src/container/TreeContainer/Base/TreeNode.ts
  src/container/TreeContainer/Base/index.ts
  src/container/TreeContainer/OrderedMap.ts
  src/utils/checkNotObject.ts
  test/HashContainerTest/HashMap.test.ts
  test/HashContainerTest/HashSet.test.ts
  test/utils/generateRandom.ts
Labels: enhancement, coverage, performance, refactor
